# Generated by Django 5.1.6 on 2025-02-23 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultimediaEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('equipment_type', models.CharField(choices=[('CAM', 'Camera'), ('MIC', 'Microphone'), ('PRJ', 'Projector'), ('LAP', 'Laptop'), ('STD', 'Studio'), ('AUD', 'Audio Equipment'), ('VID', 'Video Equipment'), ('OTH', 'Other')], max_length=3)),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity_available', models.IntegerField(default=1)),
                ('max_reservation_hours', models.IntegerField(default=4)),
                ('requires_training', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Multimedia Equipment',
                'verbose_name_plural': 'Multimedia Equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(auto_now_add=True)),
                ('return_time', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.TextField()),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('condition_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.multimediaequipment')),
            ],
            options={
                'verbose_name': 'Equipment Usage',
                'verbose_name_plural': 'Equipment Usage',
            },
        ),
    ]
