# Generated by Django 5.1.6 on 2025-02-23 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='condition',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs Repair')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='last_maintained',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='serial_number',
            field=models.CharField(default='TEMP-SN', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='equipment_type',
            field=models.CharField(choices=[('AUD', 'Audio Equipment'), ('VID', 'Video Equipment'), ('OTH', 'Other')], max_length=3),
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
            },
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demoapp.equipmentcategory'),
        ),
        migrations.CreateModel(
            name='EquipmentUsageExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_on_return', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs Repair')], max_length=20, null=True)),
                ('notes_on_return', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_usages', to=settings.AUTH_USER_MODEL)),
                ('usage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoapp.equipmentusage')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.multimediaequipment')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultimediaEquipmentExtended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_repair', 'Needs Repair')], default='good', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_maintained', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demoapp.equipmentcategory')),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demoapp.multimediaequipment')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=10)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
