# Generated by Django 5.1.6 on 2025-02-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_equipment_usage_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentusage',
            options={'ordering': ['-checkout_time'], 'verbose_name': 'Equipment Usage', 'verbose_name_plural': 'Equipment Usage'},
        ),
        migrations.AlterField(
            model_name='equipmentusage',
            name='checkout_time',
            field=models.DateTimeField(),
        ),
    ]
