# Generated by Django 5.1.6 on 2025-02-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_alter_equipmentusage_options_and_more'),
        ('demoapp', '0003_alter_userprofile_user'),
    ]

    operations = [
    ]
