# Generated by Django 5.1.6 on 2025-02-23 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demoapp', '0004_userprofile'),
    ]

    operations = [
        migrations.RunSQL(
            # Drop the old table and recreate it with the correct schema
            """
            DROP TABLE IF EXISTS demoapp_userprofile;
            CREATE TABLE demoapp_userprofile (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_type varchar(10) NOT NULL DEFAULT 'student',
                number varchar(20) NOT NULL DEFAULT '',
                user_id integer NOT NULL REFERENCES auth_user(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
            );
            CREATE UNIQUE INDEX demoapp_userprofile_user_id ON demoapp_userprofile(user_id);
            """
        ),
    ]
