# Generated by Django 5.1.6 on 2025-02-26 16:21

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('demoapp', '0004_merge_20250226_1600'),
    ]

    operations = [
        # No operations needed - this migration just ensures we're in a clean state
    ]
