# Generated by Django 5.1.6 on 2025-03-16 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_multimediaequipment_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimediaequipmentextended',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='multimediaequipmentextended',
            name='category',
        ),
        migrations.RemoveField(
            model_name='multimediaequipmentextended',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='inventory_number',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='last_maintained',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='max_reservation_hours',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='min_alert_threshold',
        ),
        migrations.RemoveField(
            model_name='multimediaequipment',
            name='requires_training',
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='is_group_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='categories',
            field=models.ManyToManyField(blank=True, to='demoapp.equipmentcategory'),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multimediaequipment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='equipment_type',
            field=models.CharField(choices=[('AUD', 'Audio Equipment'), ('VID', 'Video Equipment'), ('OTH', 'Other')], default='OTH', max_length=3),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_images/'),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='multimediaequipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='demoapp.studentgroup')),
            ],
            options={
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='demoapp.studentgroup'),
        ),
        migrations.DeleteModel(
            name='EquipmentUsageExtended',
        ),
        migrations.DeleteModel(
            name='MultimediaEquipmentExtended',
        ),
    ]
