# Generated by Django 5.1.6 on 2025-03-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_blacklistedstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='description',
            new_name='issue_description',
        ),
    ]
