# Generated by Django 5.1.6 on 2025-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0014_equipmentusage_photo_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklistedstudent',
            options={'ordering': ['-blacklisted_date'], 'verbose_name': 'Blacklisted Student', 'verbose_name_plural': 'Blacklisted Students'},
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blacklistedstudent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipmentusage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('pending_photo', 'Photo Required'), ('photo_submitted', 'Photo Submitted'), ('rejected', 'Rejected'), ('checked_out', 'Checked Out'), ('returned', 'Returned'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
